[[redirects]]
  from = "/datasheets/D1"
  to = "/files/datasheets/set_01/d1_periodic_table_of_elements.pdf"
  status = 200
  force = true

[[redirects]]
  from = "/datasheets/D2"
  to = "/files/datasheets/set_01/d2_properties_of_elements.pdf"
  status = 200
  force = true

[[redirects]]
  from = "/datasheets/D3"
  to = "/files/datasheets/set_01/d3_properties_of_isotopes.pdf"
  status = 200
  force = true

[[redirects]]
  from = "/datasheets/sources"
  to = "/files/datasheets/set_01/sources.pdf"
  status = 200
  force = true

[[redirects]]
  from = "/elements/hydrogen/datasheet"
  to = "/files/elements/hydrogen.pdf"
  status = 200
  force = true

[[redirects]]
  from = "/elements/helium/datasheet"
  to = "/files/elements/helium.pdf"
  status = 200
  force = true

[[redirects]]
  from = "/elements/lithium/datasheet"
  to = "/files/elements/lithium.pdf"
  status = 200
  force = true

[[redirects]]
  from = "/elements/beryllium/datasheet"
  to = "/files/elements/beryllium.pdf"
  status = 200
  force = true

[[redirects]]
  from = "/periodic_table/styles/full"
  to = "/files/periodic_tables/full.png"
  status = 200
  force = true

[[redirects]]
  from = "/periodic_table/styles/blank"
  to = "/files/periodic_tables/blank.png"
  status = 200
  force = true

[[redirects]]
  from = "/periodic_table/styles/electronic_blocks"
  to = "/files/periodic_tables/electronic_blocks.png"
  status = 200
  force = true

[[redirects]]
  from = "/periodic_table/styles/extended_group_numbers"
  to = "/files/periodic_tables/extended_group_numbers.png"
  status = 200
  force = true

[[redirects]]
  from = "/periodic_table/styles/extended_group_numbers_+_names"
  to = "/files/periodic_tables/extended_group_numbers_+_names.png"
  status = 200
  force = true

[[redirects]]
  from = "/periodic_table/styles/simplified_group_numbers"
  to = "/files/periodic_tables/simplified_group_numbers.png"
  status = 200
  force = true

[[redirects]]
  from = "/periodic_table/styles/simplified_group_numbers_+_names"
  to = "/files/periodic_tables/simplified_group_numbers_+_names.png"
  status = 200
  force = true

[[redirects]]
  from = "/hpq/log"
  to = "/files/hpq/AQA-7992-CRF-22.pdf"
  status = 200
  force = true

[[redirects]]
  from = "/elements/*"
  to = "/elements/404.html"
  status = 404
  force = false

[[redirects]]
  from = "/particles/*"
  to = "/particles/404.html"
  status = 404
  force = false

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = false